### ISSUE TITLE
Put list of papers in JSON or YAML

### ISSUE THREAD

**Issue by tritemio** [tritemio/reproducible_papers#2]
This list can become useful if it can be machine-processed and divided into categories.

Instead of a simple markdown list, it would better to keep the list of papers in JSON or YAML.

This is a brain-dump of what fields the schema could include (using YAML for simplicity):

``` yaml
papers:
    - title: Adaptive Engagement of Cognitive Control in Context-Dependent Decision Making
      authors:
        - Michael L. Waskom
        - Michael C. Frank
        - Anthony D. Wagner
      year:       2016
      doi:        10.1093/cercor/bhv333
      url:        http://doi.org/10.1093/cercor/bhv333 # paper's URL
      journal:    Cerebral Cortex
      repository: https://github.com/WagnerLabPapers/Waskom_CerebCortex_InPress
      language:
          - python
          - r
          - c++
      platform:
          - linux
          - osx
          - windows
      system_environment: # one or more of: conda, docker, etc
                          # whatever tech make the software environment "reproducible"
          - docker
          - conda  # let's pretend a conda env is used inside docker
          - packtr
      execution:   # tech used to "automate" running the analysis
          - make
          - jupyter notebook
          - python
          - perl
          - bash
      reporting: # tech used to present results (if any).
                 # if scripts create only the paper's figures don't put anything.
          - jupyter notebook
          - knitr
          - latex
      online_execution: # if possible to execute the analysis online put
                        # the name of the service here
          - mybinder

    - title: How much of the world is woody?
      authors: [Richard G. FitzJohn, Matthew W. Pennell, Amy E. Zanne, Peter F. Stevens, David C. Tank, William K. Cornwell]
      year:       2014
      doi:        10.1111/1365-2745.12260
      url:        http://doi.org/10.1111/1365-2745.12260 # paper's URL
      journal:    Journal of Ecology
      repository: https://github.com/richfitz/wood
```
